# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170925_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Ec_User',
        ),
    ]
