# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170925_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
    ]
