# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170925_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec_user',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ec_user',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
