# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170925_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec_user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
