# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170925_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ec_Admin',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
