# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_ec_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(default='default.png', upload_to='product_images/'),
        ),
    ]
